export enum Types {
    TODO_FETCH_REQUEST = 'TODO_FETCH_REQUEST',
    TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS',
    TODO_FETCH_FAILURE = 'TODO_FETCH_FAILURE',
    TODO_POST_SUCCESS = 'TODO_POST_SUCCESS',
    TODO_POST_FAILURE = 'TODO_POST_FAILURE',
    TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS',
    TODO_DELETE_FAILURE = 'TODO_DELETE_FAILURE',
    TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS',
    TODO_UPDATE_FAILURE = 'TODO_UPDATE_FAILURE',
    YT_ITEMS_FETCH_REQUEST = 'YT_ITEMS_FETCH_REQUEST',
    YT_ITEMS_FETCH_SUCCESS = 'YT_ITEMS_FETCH_SUCCESS',
    YT_ITEMS_FETCH_FAILURE = 'YT_ITEMS_FETCH_FAILURE',
}